// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: String.fromEnvironment('FIREBASE_API_KEY', defaultValue: ''),
        appId: String.fromEnvironment('FIREBASE_APP_ID', defaultValue: ''),
        messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: ''),
        projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: ''),
        storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: ''),
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ieB429gFtd52QO5kedHxnrYyzmC2VzQ',
    appId: '1:665426667066:android:2b1c168584630e6df63703',
    messagingSenderId: '665426667066',
    projectId: 'auth-app-f3294',
    storageBucket: 'auth-app-f3294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOXCo8FoLaPVs0y21tpg-xXl3iodhaJnY',
    appId: '1:665426667066:ios:f515dc231f7adbe8f63703',
    messagingSenderId: '665426667066',
    projectId: 'auth-app-f3294',
    storageBucket: 'auth-app-f3294.firebasestorage.app',
    androidClientId: '665426667066-15h0eplb24k79ulgqgrr56s30atmmcp3.apps.googleusercontent.com',
    iosClientId: '665426667066-2hegm8sa6ij527lamiju230ushoct349.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureAuthMvvm',
  );
}
